const initialState={
    user:{
        isSignedIn:false,
        uid:"",
        email:"",
        updateTime:""
    },
    profile:{
        name:"name",
        howToGetProduction:[],
        scale:[],
        color:[],
        series:[]
    },
    userError:{
        userError:false
    },
    loading:{
        loading:false
    },
    record:{
        name:""
    },
    recordError:{
        nameNoValue:false,
        nameOverValue:false,
        commentNoValue:false,
        commentOverValue:false,
        howToGetProductionOverValue:false,
        scaleOver:false,
        colorOver:false,
        seriesOver:false,
    },
    productions:{
        productions:[],
    },
    production:{
        userName:"",
        uid:"",
        productionName:"",
        scale:"",
        series:"",
        color:"",
        howToGet:"",
        photoUrl:"",
        situation:""
    },
    myProductions:{
        myProductions:[]
    },
    comments:{
        comments:[
            
        ]
    }
}
export default initialState
