const initialState={
    user:{
        isSignedIn:false,
        uid:"",
        email:"",
        updateTime:""
    },
    profile:{
        name:"name",
        howToGetProduction:[]
    },
    userError:{
        userError:false
    },
    loading:{
        loading:false
    },
    record:{
        name:""
    },
    recordError:{
        nameNoValue:false,
        nameOverValue:false,
        commentNoValue:false,
        commentOverValue:false,
        howToGetProductionOverValue:false
    },
    productions:{
        productions:[
            [
                {
                    id:"",
                    name:""
                }
            ]
        ]
    }
}
export default initialState
